version: '3'

services: 
 database:
  image: 'postgres:latest'
  ports:
    - 5432:5432

  volumes:
    - ./db-data/:/var/lib/postgresql/data=rwx/

  environment: 
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_DB: default_database