version: '3.9'

services:
  #Backend build
  api:
    build: ./Backend
    command: python manage.py run -h 0.0.0.0
    depends_on:
      - database
    ports:
      - 5000:5000
    env_file:
      - ./Backend/env.dev
   
    volumes:
        - .:/code

  #Frontend Build
  web:
    build: ./frontend
    image: frontend
    container_name: frontend
    restart: always
    environment:
        PORT: 4200
        PROXY_API: http://quizme:5000/
        API_URL: 'http://localhost:5000'
    ports:
    - "4200:80"

  #DB build
  database:
    
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onlineexam-database-1
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    volumes:
      #- postgres_data:/var/lib/postgresql/data/
      - ./db-data/:/var/lib/postgresql/data=rwx/

      
