version: '3.9'

services:
  #Backend build
  api:
    build: ./Backend
    depends_on:
      - database
    ports:
      - 5000:5000

    environment:
      Stage: development
      DATABASE_URL: postgresql://postgres:postgres@0.0.0.0:5432/onlineexam-database-1
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:postgres@database/
    volumes:
        - .:/code

  #Frontend Build
  web:
    build: ./frontend
    image: frontend
    container_name: frontend
    restart: always
    environment:
        PORT: 4200
        PROXY_API: http://quizme:5000/
        API_URL: 'http://localhost:5000'
    ports:
    - "4200:80"
   # expose: 
  #  - "4200"
    
  #DB build
  database:
    
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onlineexam-database-1
    image: 'postgres:latest'
    ports:
      - 5432:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data=rwx/

      
