version: '3.9'

services:
 web:
  build: ./frontend
  image: frontend
  container_name: frontend
  restart: always
  environment:
      PORT: 5000
      PROXY_API: http://quizme:5432/
  ports:
   - "5000:80"
  expose: 
   - "5000"
  env_file:
   - ./env.dev
  links:
   - database
 
 database:
  build: .
  image: 'postgres:latest'
  ports:
    - 5432:5432
  volumes:
    - ./db-data/:/var/lib/postgresql/data=rwx/

  environment: 
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_DB: onlineexam-database-1

volumes:
  postgres_data: