version: '3'

services:
 web:
  build: .
  volumes:
   - src:/src
  ports:
   - "5000:5000"
  env_file:
   - ./.env.dev
  links:
   - database
 database:
  image: 'postgres:latest'
  ports:
    - 5432:5432

  volumes:
    - ./db-data/:/var/lib/postgresql/data=rwx/

  environment: 
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_DB: default_database

volumes:
  app: {}